import { useEffect, useState } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { CheckCircle2, Circle, ChevronRight, ExternalLink, Flag, Printer, Rocket, Shuffle, Trophy, Users, X, ArrowLeft, Play, Pause, RotateCcw, Target, Wrench, AlertTriangle, Check } from 'lucide-react';
import { HARDWARE, MISSIONS, SCRATCH_PROJECTS } from '../domain/content';
import { completionPercent, overallPercent, parseState, serializeState } from '../application/progress';
import { trackerError, trackerNext, yawAdjustment, type Point } from '../application/tracker';
import { useAppState, useCompleted, resetState } from '../presentation/hooks';
import { Icon } from '../presentation/icons';

function ProgressRing({ percent }: { percent: number }) { return <div className="progress-ring" style={{ '--progress': `${percent * 3.6}deg` } as React.CSSProperties}><span>{percent}%</span></div>; }
function Header({ percent }: { percent: number }) { return <header className="header app-chrome"><NavLink to="/" className="brand"><span className="bot-icon"><span>⊙</span></span><span><small>Fifth Grade Coding Humanoid · Learning Path 1</small><strong>TobyBot Mission Control</strong></span></NavLink><div className="header-actions"><nav className="tabs" aria-label="Main navigation"><NavLink to="/">TobyBot Mission Control</NavLink><NavLink to="/projects">⌘ Scratch projects</NavLink><NavLink to="/troubleshooting"><Wrench size={13} /> Trouble shoots</NavLink><NavLink to="/print"><Printer size={13} /> Teacher print view</NavLink></nav><div className="overall"><ProgressRing percent={percent} /><span><small>Program complete</small><b>{percent === 100 ? 'All missions flown' : 'In progress'}</b></span></div></div></header>; }
function HardwareStrip() { return <section className="hardware-grid">{HARDWARE.map((item) => <article className="hardware" key={item.name} style={{ borderColor: `${item.color}55` }}><span className="icon-box" style={{ background: `${item.color}22`, color: item.color }}><Icon name={item.icon} size={17} /></span><div><small style={{ color: item.color }}>{item.tag}</small><b>{item.name}</b><p>{item.description}</p></div></article>)}</section>; }
function CheckItem({ checked, onClick, children, color }: { checked: boolean; onClick: () => void; children: React.ReactNode; color: string }) { return <button className="check-item" onClick={onClick}>{checked ? <CheckCircle2 color={color} size={17} /> : <Circle color="#5b6390" size={17} />}<span className={checked ? 'checked' : ''}>{children}</span></button>; }
function PairingTool({ roster, updateRoster }: { roster: string[]; updateRoster: (roster: string[]) => void }) { const [input, setInput] = useState(''); const [pairs, setPairs] = useState<Array<{ navigator: string; pilot: string | null }> | null>(null); const add = () => { const name = input.trim(); if (name) { updateRoster([...roster, name]); setInput(''); } }; const shuffle = () => { const copy = [...roster].sort(() => Math.random() - .5); setPairs(Array.from({ length: Math.ceil(copy.length / 2) }, (_, i) => ({ navigator: copy[i * 2], pilot: copy[i * 2 + 1] ?? null }))); }; return <section className="panel"><h3><Users size={17} /> Navigator &amp; Pilot pairing</h3><p className="muted">One student tracks the logic on paper, the other tests it on TonyBot.</p><div className="input-row"><input aria-label="Add a student name" value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && add()} placeholder="Add a student name" /><button className="button" onClick={add}>Add</button></div><div className="chips">{roster.map((name, index) => <span className="chip" key={`${name}-${index}`}>{name}<button aria-label={`Remove ${name}`} onClick={() => updateRoster(roster.filter((_, i) => i !== index))}><X size={12} /></button></span>)}</div><button className="primary wide" onClick={shuffle} disabled={roster.length < 2}><Shuffle size={15} /> Shuffle pairs</button>{pairs && <div className="pairs">{pairs.map((pair, i) => <div className="pair" key={i}><span className="badge blue">Navigator · {pair.navigator}</span>{pair.pilot ? <span className="badge orange">Pilot · {pair.pilot}</span> : <small className="muted">solo this round</small>}</div>)}</div>}</section>; }
function MissionControl({ state, update }: { state: ReturnType<typeof useAppState>[0]; update: ReturnType<typeof useAppState>[1] }) { const [selected, setSelected] = useState(1); const { completed, toggle } = useCompleted(state, update); const mission = MISSIONS.find((item) => item.id === selected)!; return <><HardwareStrip /><main className="mission-layout"><aside><h2 className="section-label">◆ Mission path</h2>{MISSIONS.map((item, index) => <div key={item.id}><button className={`mission-node ${item.id === selected ? 'active' : ''}`} style={{ '--accent': item.color } as React.CSSProperties} onClick={() => setSelected(item.id)}><span className="node-dot">{completionPercent(item, completed) === 100 ? <Trophy size={13} /> : item.id}</span><span><small>{item.code} · {item.level}</small><b>{item.name}</b></span><ChevronRight size={16} /></button>{index < MISSIONS.length - 1 && <div className="connector" />}</div>)}<PairingTool roster={state.roster} updateRoster={(roster) => update({ ...state, roster })} /></aside><section className="detail-card" style={{ borderTopColor: mission.color }}><div className="eyebrow" style={{ color: mission.color }}><Rocket size={17} /> {mission.code} · {mission.level}</div><h1>{mission.name}</h1><p className="lead">{mission.focus}</p><ProgressBar percent={completionPercent(mission, completed)} color={mission.color} /><h2 className="block-label">Learning objectives</h2><div className="stack">{mission.objectives.map((objective, i) => { const key = `p${mission.id}-obj-${i}`; return <CheckItem key={key} checked={completed.has(key)} onClick={() => toggle(key)} color={mission.color}>{objective}</CheckItem>; })}</div><h2 className="block-label">Core activities</h2><div className="stack">{mission.activities.map((activity, i) => { const key = `p${mission.id}-act-${i}`; return <article className="activity" key={key}><button className="icon-button" aria-label={`Complete ${activity.title}`} onClick={() => toggle(key)}>{completed.has(key) ? <CheckCircle2 color={mission.color} /> : <Circle color="#5b6390" />}</button><div><h3 className={completed.has(key) ? 'checked' : ''}>{activity.title}</h3><p>{activity.detail}</p>{activity.walkthrough && <NavLink className="outline-button" to="/walkthrough">Open code walkthrough <ChevronRight size={13} /></NavLink>}</div></article>; })}</div><div className="assessment" style={{ borderColor: `${mission.color}55` }}><strong style={{ color: mission.color }}><Flag size={15} /> Mission checkpoint</strong><p>{mission.assessment}</p></div></section></main></>; }
function ProgressBar({ percent, color }: { percent: number; color: string }) { return <div className="progress-bar"><span style={{ width: `${percent}%`, background: color }} /></div>; }
function Projects() { return <section className="page-card"><div className="eyebrow blue-text">⌘ Mission 2 · WonderCode / Scratch</div><h1>Scratch Projects</h1><p className="lead">Three ready-to-build WonderCode routines with real Scratch-style setup steps and a safety-first testing order.</p><div className="projects-grid">{SCRATCH_PROJECTS.map((project) => <article className="project" key={project.id} style={{ borderColor: `${project.color}55` }}><span className="icon-box" style={{ background: `${project.color}22`, color: project.color }}><Icon name={project.icon} size={20} /></span><small style={{ color: project.color }}>{project.tag}</small><h2>{project.title}</h2><p>{project.description}</p><div className="project-links"><a href={project.localUrl}>Open local demo <ExternalLink size={13} /></a><a href={project.externalUrl} target="_blank" rel="noreferrer">External artifact <ExternalLink size={13} /></a></div></article>)}</div></section>; }
function Troubleshooting() {
  const steps = [
    ['Open the software', <>Launch the <a href="https://docs.hiwonder.com/projects/Tonybot/en/latest/docs/2.app_control.html" target="_blank" rel="noreferrer"><strong>Hiwonder Python Editor software</strong></a> on your computer.</>],
    ['Connect the robot', <>Use the connection cable to plug TonyBot into your PC. Click <strong>Connect</strong> in the software’s top menu. The connection icon turns green when pairing succeeds.</>],
    ['Locate the main file', <>In the sidebar, find the section labeled <strong>Device (Connected)</strong>.</>],
    ['Delete and trigger reset', <>Right-click the file named <code>main.py</code> and select <strong>Delete</strong>.</>],
    ['Reboot TonyBot', <>Manually restart TonyBot. On boot, its self-recovery routine should reinstall the original factory program automatically.</>]
  ];
  return <section className="page-card troubleshooting-page"><div className="eyebrow orange-text"><Wrench size={17} /> Support guide · Factory reset</div><h1>Restore factory application control</h1><p className="lead">To factory reset the <a href="https://www.google.com/search?q=HiWonder+TonyBot" target="_blank" rel="noreferrer"><strong>HiWonder TonyBot</strong></a> and restore its default application control program, use the manufacturer’s desktop software to clear user-loaded custom code.</p><div className="warning-callout"><AlertTriangle size={20} /><p>The TonyBot system uses a self-recovery backup partition. Deleting the active <code>main.py</code> script causes the controller to reload its factory default state. Delete only the intended user file and keep the robot connected during the operation.</p></div><ol className="troubleshooting-steps">{steps.map(([title, detail], index) => <li key={index}><span className="step-number">{index + 1}</span><div><h2>{title}</h2><p>{detail}</p></div><Check size={18} className="step-check" /></li>)}</ol><div className="source-callout"><strong>Official reference</strong><a href="https://docs.hiwonder.com/projects/Tonybot/en/latest/docs/2.app_control.html" target="_blank" rel="noreferrer">TonyBot App Control documentation <ExternalLink size={13} /></a></div></section>;
}
function Walkthrough() {
  const [open, setOpen] = useState('see');
  const [ball, setBall] = useState<Point>({ x: 250, y: 90 });
  const [reticle, setReticle] = useState<Point>({ x: 150, y: 90 });
  const [running, setRunning] = useState(false);
  const [dragging, setDragging] = useState(false);
  useEffect(() => {
    if (!running) return;
    const timer = window.setInterval(() => setReticle((point) => trackerNext(point, ball)), 60);
    return () => window.clearInterval(timer);
  }, [ball, running]);
  const reset = () => { setRunning(false); setBall({ x: 250, y: 90 }); setReticle({ x: 150, y: 90 }); };
  const moveBall = (event: React.PointerEvent<SVGSVGElement>) => {
    if (!dragging) return;
    const rect = event.currentTarget.getBoundingClientRect();
    setBall({ x: Math.max(14, Math.min(286, ((event.clientX - rect.left) / rect.width) * 300)), y: Math.max(14, Math.min(166, ((event.clientY - rect.top) / rect.height) * 180)) });
  };
  const steps = [
    ['see', '1. See the ball', 'The camera identifies only pixels inside a chosen color range.', 'frame = camera.read()\nmask = threshold(frame, color="orange")\nball = find_largest_blob(mask)'],
    ['locate', '2. Find its position', 'The ball center is compared with the frame center to calculate error.', 'cx, cy = ball.center\nerror_x = cx - frame.width / 2'],
    ['adjust', '3. Adjust the yaw servo', 'A proportional controller turns more when the error is larger.', 'yaw_angle += error_x * gain\nset_servo("yaw", clamp(yaw_angle, -90, 90))'],
    ['loop', '4. Repeat, forever', 'The loop keeps re-centering the ball as it moves.', 'while True:\n    track_ball()\n    re_center_servo()']
  ];
  return <section className="page-card"><NavLink className="back-link" to="/"><ArrowLeft size={15} /> Back to mission control</NavLink><div className="eyebrow green-text"><Target size={17} /> Mission 4 · Code walkthrough</div><h1>The Autonomous Tracker</h1><p className="lead">Drag the ball around the frame, then run the tracking loop to see the proportional-control idea catch up.</p><div className="tracker-grid"><div><svg className="tracker-frame" viewBox="0 0 300 180" role="img" aria-label="Interactive ball tracking simulator" onPointerDown={(event) => { setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={() => setDragging(false)} onPointerMove={moveBall}><rect width="300" height="180" rx="10" fill="#0b0e1f" /><line x1="150" x2="150" y2="180" stroke="#2a3160" strokeDasharray="4 4" /><circle cx={ball.x} cy={ball.y} r="12" fill="#ff8a5b" /><circle cx={reticle.x} cy={reticle.y} r="16" fill="none" stroke="#6ee7b7" strokeWidth="2" /><line x1={reticle.x - 22} x2={reticle.x + 22} y1={reticle.y} y2={reticle.y} stroke="#6ee7b7" /><line x1={reticle.x} x2={reticle.x} y1={reticle.y - 22} y2={reticle.y + 22} stroke="#6ee7b7" /></svg><div className="tracker-controls"><button className="primary" onClick={() => setRunning((value) => !value)}>{running ? <Pause size={14} /> : <Play size={14} />} {running ? 'Pause' : 'Run tracking loop'}</button><button className="button" onClick={reset}><RotateCcw size={13} /> Reset</button></div><div className="telemetry"><span><small>error_x</small><b>{trackerError(reticle, ball)}px</b></span><span><small>yaw adjust</small><b>{yawAdjustment(trackerError(reticle, ball))}°</b></span></div></div><div className="steps">{steps.map(([id, title, explanation, code]) => <article className={`step ${open === id ? 'open' : ''}`} key={id}><button onClick={() => setOpen(open === id ? '' : id)}><span><Icon name={id === 'see' ? 'eye' : id === 'loop' ? 'refresh' : 'radar'} size={15} />{title}</span><ChevronRight size={15} /></button>{open === id && <div><p>{explanation}</p><pre>{code}</pre></div>}</article>)}</div></div></section>;
}
function PrintView() { return <section className="print-page"><div className="print-toolbar"><button className="button" onClick={() => window.print()}><Printer size={15} /> Print this page</button><span>Prints in light mode, one mission per section.</span></div><header><small>HiWonder TonyBot · Grade 5 Curriculum</small><h1>Teacher Reference — All Missions</h1><p>Class: _______________________ &nbsp;&nbsp; Date: ________________________</p></header>{MISSIONS.map((mission) => <article className="print-section" key={mission.id} style={{ borderLeftColor: mission.color }}><h2>{mission.code} · {mission.level} — {mission.name}</h2><p>{mission.focus}</p><h3>Learning objectives</h3><ul>{mission.objectives.map((item) => <li key={item}>□ {item}</li>)}</ul><h3>Core activities</h3><ul>{mission.activities.map((item) => <li key={item.title}>□ <strong>{item.title}.</strong> {item.detail}</li>)}</ul><div className="print-assessment"><strong>Mission checkpoint:</strong> {mission.assessment}</div></article>)}<footer>Safety note: keep TonyBot tethered or suspended by a harness during initial code testing on every new routine.</footer></section>; }
function App() { const [state, update] = useAppState(); const percent = overallPercent(MISSIONS, new Set(state.completed)); const exportState = () => { const blob = new Blob([serializeState(state)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'tonybot-progress.json'; link.click(); URL.revokeObjectURL(url); }; const importState = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; file.text().then((text) => { try { update(parseState(text)); alert('Progress imported.'); } catch (error) { alert(error instanceof Error ? error.message : 'Could not import progress.'); } }); event.target.value = ''; }; return <div className="app"><Header percent={percent} /><div className="content"><Routes><Route path="/" element={<MissionControl state={state} update={update} />} /><Route path="/projects" element={<Projects />} /><Route path="/troubleshooting" element={<Troubleshooting />} /><Route path="/walkthrough" element={<Walkthrough />} /><Route path="/print" element={<PrintView />} /></Routes><div className="footer app-chrome"><span>Tethered or harnessed testing recommended for every new routine — gravity does not do retakes.</span><div><button className="text-button" onClick={exportState}>Export progress</button><label className="text-button">Import progress<input type="file" accept="application/json" hidden onChange={importState} /></label><button className="text-button" onClick={() => resetState(update)}>Reset all</button></div></div></div></div>; }

export default App;
