import type { HardwareFeature, Mission, ScratchProject, TrackerStep } from './types';

export const HARDWARE: HardwareFeature[] = [
  { tag: 'Actuation', name: '17 Serial Bus Servos', icon: 'cpu', color: '#ff8a5b', description: 'Feedback angle, temperature, and voltage so TonyBot can walk, dance, and do push-ups without losing balance.' },
  { tag: 'AI Vision', name: 'ESP32-S3 HD Camera', icon: 'eye', color: '#4fd1ff', description: 'A 2MP camera that streams over Wi-Fi and can track colors, recognize faces, and follow lines.' },
  { tag: 'Voice', name: 'WonderEcho Module', icon: 'mic', color: '#c6a6ff', description: 'Listens for spoken commands and runs the matching action right on the robot — no internet needed.' },
  { tag: 'Sensors', name: 'Ultrasonic + IMU', icon: 'radar', color: '#6ee7b7', description: 'Measures distance to spot obstacles and tracks tilt so TonyBot knows when it is about to fall.' }
];

export const MISSIONS: Mission[] = [
  { id: 1, code: 'Mission 1', name: 'Foundations & Kinesthetic Logic', level: 'Beginner', color: '#ff8a5b', focus: 'Understand the hardware, feel how balance works, and build choreography with no syntax required.', objectives: ['Explain degrees of freedom and how joints mirror human movement', 'Use the PC debugging software to pose TonyBot’s arms and legs', 'Build a sequence-based action group'], activities: [{ title: 'Digital Marionette', detail: 'Use the graphical slider software to pose TonyBot frame by frame, recording a custom 5-second victory dance.' }, { title: 'App Telemetry & Remote Control', detail: 'Drive TonyBot with the tablet app and watch how shifting its center of gravity changes how stable each step feels.' }], assessment: 'Compile and export a 3-step action sequence — Bow → Stand → Wave — and play it back on the real robot.' },
  { id: 2, code: 'Mission 2', name: 'Visual Logic & Block-Based Programming', level: 'Intermediate I', color: '#4fd1ff', focus: 'Bring in loops, conditionals, and events using Scratch blocks, wired to real sensors.', objectives: ['Use sequences, repeat loops, and if–else blocks correctly', 'Read ultrasonic and IMU sensor values inside a logic loop'], activities: [{ title: 'Smart Guard Obstacle Avoider', detail: 'Walk forward until the ultrasonic sensor reads under 20 cm, then step back, turn right, and speak a warning.' }, { title: 'Color-Triggered Reflexes', detail: 'Wire the vision blocks so a red block triggers a happy dance and a blue block triggers a crouch.' }], assessment: 'Navigate a simple maze autonomously using only sensor-triggered block scripts.' },
  { id: 3, code: 'Mission 3', name: 'Transition to Text & Structured Logic', level: 'Intermediate II', color: '#c6a6ff', focus: 'Carry the same logic from blocks into Python syntax — functions, variables, arguments.', objectives: ['Translate a block script into an equivalent Python structure', 'Trace execution flow and debug a text-based error'], activities: [{ title: 'Voice-Activated Commands', detail: 'Map WonderEcho keywords to action groups in Python, so saying “Forward” calls walk_forward().' }, { title: 'The Balance Keepers', detail: 'Read the IMU tilt angle in code and trigger a fall-recovery or shutdown sequence when it exceeds a safe limit.' }], assessment: 'Write a script that listens for a custom voice command, checks distance with the ultrasonic sensor, and reports it back.' },
  { id: 4, code: 'Mission 4', name: 'Applied AI & Autonomous Capstone', level: 'Advanced', color: '#6ee7b7', focus: 'Combine vision, movement, and logic into one open-ended autonomous project.', objectives: ['Explain color thresholding and face tracking at a basic level', 'Design and defend an original vision-plus-movement routine'], activities: [{ title: 'The Autonomous Tracker', detail: 'Lock onto a moving colored ball with the camera feed and adjust the yaw servos to keep tracking it.', walkthrough: true }, { title: 'Capstone: The Robot Assistant', detail: 'In teams, combine face recognition, voice prompting, and movement so TonyBot greets a recognized user by name.' }], assessment: 'Present the finished routine at a maker-faire style showcase, explaining the code, the hardware, and what broke along the way.' }
];

export const SCRATCH_PROJECTS: ScratchProject[] = [
  { id: 'moonwalk', title: 'Moonwalk-Inspired Dance', icon: 'music', color: '#4fd1ff', description: 'A short, safe, moonwalk-inspired routine built from TonyBot’s prebuilt dance action groups — intro, repeated backward glide, accent turn, and a safe stop.', tag: 'Mission 2 · Scratch', localUrl: 'projects/moonwalk-inspired.html', externalUrl: 'https://claude.ai/artifact/71ay8ZcbDaqRigkinNaC2a' },
  { id: 'breathing-light', title: 'Breathing Light', icon: 'sparkles', color: '#8c6bff', description: 'The ultrasonic RGB LEDs smoothly brighten and dim like a breathing light, with an optional multicolor cycling version.', tag: 'Mission 2 · Scratch', localUrl: 'projects/breathing-light.html', externalUrl: 'https://claude.ai/artifact/N6oXc3rZJifB1uzUeL1hhh' },
  { id: 'walk-circle', title: 'Walk in a Circle', icon: 'refresh', color: '#4fa3ff', description: 'Repeated forward-and-turn segments trace a circular path, with a configurable Walk Circle block for segment count and direction.', tag: 'Mission 2 · Scratch', localUrl: 'projects/walk-in-circle.html', externalUrl: 'https://claude.ai/artifact/RiRPQeh2XUQdBTQoB2N3Bm' }
];

export const TRACKER_STEPS: TrackerStep[] = [
  { id: 'see', title: '1. See the ball', icon: 'eye', explain: 'The camera grabs a frame and looks only for pixels inside a chosen color range — this is color thresholding. Everything else in the frame is ignored.', code: `frame = camera.read()\nmask = threshold(frame, color="orange",\n                  low=(5,150,150), high=(20,255,255))\nball = find_largest_blob(mask)` },
  { id: 'locate', title: '2. Find its position', icon: 'radar', explain: 'Once a blob is found, its center point tells us where the ball is in the frame. We compare that to the frame center to get an error.', code: `if ball is not None:\n    cx, cy = ball.center\n    error_x = cx - frame.width / 2\nelse:\n    error_x = 0  # ball not visible` },
  { id: 'adjust', title: '3. Adjust the yaw servo', icon: 'radar', explain: 'A small proportional controller: the bigger the error, the bigger the correction. Gain controls how aggressively TonyBot turns.', code: `gain = 0.05\nyaw_angle += error_x * gain\nyaw_angle = clamp(yaw_angle, -90, 90)\nset_servo("yaw", yaw_angle)` },
  { id: 'loop', title: '4. Repeat, forever', icon: 'refresh', explain: 'Wrap steps 1–3 in a loop that runs continuously, so TonyBot keeps re-centering the ball as it moves.', code: `while True:\n    frame = camera.read()\n    ball = find_largest_blob(threshold(frame))\n    if ball is not None:\n        error_x = ball.center[0] - frame.width / 2\n        set_servo("yaw", clamp(error_x * gain, -90, 90))` }
];
